name: testing_flutter_apps_tuto
description: A new Flutter project learning testing.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  provider: ^6.0.5
  flutter_lorem: ^2.0.0
  get: ^4.6.5

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  integration_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  mocktail: ^0.3.0

flutter:

  uses-material-design: true
